use agent_evolution::{
    ComponentInspectionRequest, ComponentInspector, ComponentInspectorFailure, PluginBuildRequest,
    PluginBuildStep, PluginBuilderWorker, PluginBuilderWorkerConfig, PluginBuilderWorkerError,
    PluginDependencyPolicy, PluginWorkspaceManifest, ProcessOutput, ProcessRequest, ProcessRunner,
    ProcessRunnerFailure, RealProcessRunner, TrustedComponentInspection,
};
use agent_evolution_protocol::{
    ArtifactDigest, CandidateId, CapabilityProfile, ComponentInterfaceSnapshot, MutationId,
    PluginCapabilitySet, PluginSourceArtifact, PluginSourceFile,
    COMPONENT_INTERFACE_SNAPSHOT_SCHEMA_VERSION,
};
use sha2::{Digest, Sha256};
use std::{
    cell::Cell,
    collections::BTreeMap,
    fs,
    path::PathBuf,
    rc::Rc,
    time::{Duration, Instant},
};
use uuid::Uuid;

const PLUGIN_ID: &str = "example.plugin";
const PLUGIN_SCOPE: &str = "plugins/example";
const COMPONENT_BYTES: &[u8] = b"\0asm\x01\0\0\0trusted-component";

/// 自动清理 Worker 测试创建的专用目录。
struct TestRoot(PathBuf);

impl TestRoot {
    /// 创建名称不可预测的真实临时目录。
    fn new(label: &str) -> Self {
        let path = std::env::temp_dir().join(format!(
            "lucia-plugin-builder-{label}-{}",
            Uuid::new_v4().simple()
        ));
        fs::create_dir(&path).expect("测试临时目录应可创建");
        Self(path)
    }
}

impl Drop for TestRoot {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}

/// 计算与生产实现一致的强类型 SHA-256 摘要。
fn digest(bytes: &[u8]) -> ArtifactDigest {
    ArtifactDigest::from_sha256_hex(format!("{:x}", Sha256::digest(bytes))).expect("摘要应合法")
}

/// 物化一个不含外部依赖、带固定锁文件的最小插件工作区。
fn dependency_plan(root: &TestRoot) -> agent_evolution::ValidatedPluginDependencyPlan {
    let files = BTreeMap::from([
        (
            format!("{PLUGIN_SCOPE}/Cargo.toml"),
            br#"[package]
name = "example-plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
"#
            .to_vec(),
        ),
        (
            format!("{PLUGIN_SCOPE}/Cargo.lock"),
            b"# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"example-plugin\"\nversion = \"0.1.0\"\n"
                .to_vec(),
        ),
        (
            format!("{PLUGIN_SCOPE}/src/lib.rs"),
            b"pub fn value() -> u32 {\n    1\n}\n".to_vec(),
        ),
    ]);
    for (relative, bytes) in &files {
        let path = root.0.join(relative);
        fs::create_dir_all(path.parent().expect("测试文件必须有父目录"))
            .expect("测试父目录应可创建");
        fs::write(&path, bytes).expect("测试文件应可写入");
    }
    let source_files = files
        .iter()
        .map(|(path, bytes)| PluginSourceFile {
            path: path.clone(),
            digest: digest(bytes),
            size_bytes: bytes.len() as u64,
        })
        .collect::<Vec<_>>();
    let source_digest = PluginSourceArtifact::new(PLUGIN_ID, source_files.clone())
        .expect("测试源码树应合法")
        .digest()
        .expect("测试源码摘要应可计算");
    PluginDependencyPolicy::validate(PluginWorkspaceManifest {
        root: root.0.clone(),
        plugin_id: PLUGIN_ID.to_string(),
        plugin_scope: PLUGIN_SCOPE.to_string(),
        parent_source_digest: digest(b"parent"),
        source_digest,
        patch_digest: digest(b"patch"),
        files: source_files,
    })
    .expect("测试依赖计划应通过")
}

/// 创建带固定超时和空显式环境的 Worker 配置。
fn worker_config(scratch: &TestRoot) -> PluginBuilderWorkerConfig {
    PluginBuilderWorkerConfig {
        cargo_executable: PathBuf::from("/trusted/bin/cargo"),
        scratch_parent: scratch.0.clone(),
        builder_revision: digest(b"builder-v1"),
        environment: BTreeMap::new(),
        step_timeout: Duration::from_secs(30),
    }
}

/// 创建一次与依赖计划精确绑定的构建请求。
fn build_request(plan: agent_evolution::ValidatedPluginDependencyPlan) -> PluginBuildRequest {
    PluginBuildRequest {
        dependency_plan: plan,
        proposal_digest: digest(b"proposal"),
        mutation_id: MutationId::generate(),
        candidate_id: CandidateId::generate(),
        build_id: "build-0001".to_string(),
        built_at_ms: 10,
    }
}

/// 可记录全部请求、注入失败或篡改并写出确定性 Component 的 Runner。
#[derive(Debug, Default)]
struct RecordingRunner {
    requests: Vec<ProcessRequest>,
    fail_at: Option<usize>,
    runner_error_at: Option<usize>,
    tamper_lock_at: Option<usize>,
    different_second_component: bool,
    build_count: usize,
}

impl ProcessRunner for RecordingRunner {
    fn run(&mut self, request: &ProcessRequest) -> Result<ProcessOutput, ProcessRunnerFailure> {
        let index = self.requests.len();
        self.requests.push(request.clone());
        if self.runner_error_at == Some(index) {
            return Err(ProcessRunnerFailure::new("模拟超时"));
        }
        if self.tamper_lock_at == Some(index) {
            fs::write(request.current_directory.join("Cargo.lock"), b"tampered")
                .expect("测试锁文件应可篡改");
        }
        if request.arguments.contains(&"wasm32-wasip2".to_string()) {
            self.build_count += 1;
            let target = PathBuf::from(
                request
                    .environment
                    .get("CARGO_TARGET_DIR")
                    .expect("Worker 必须注入 target"),
            );
            let output = target
                .join("wasm32-wasip2")
                .join("release")
                .join("example_plugin.wasm");
            fs::create_dir_all(output.parent().expect("产物必须有父目录"))
                .expect("产物目录应可创建");
            let bytes = if self.different_second_component && self.build_count == 2 {
                b"\0asm\x01\0\0\0different".as_slice()
            } else {
                COMPONENT_BYTES
            };
            fs::write(output, bytes).expect("模拟 Component 应可写入");
        }
        if self.fail_at == Some(index) {
            Ok(ProcessOutput::from_bytes(1, b"", b"failed"))
        } else {
            Ok(ProcessOutput::from_bytes(0, b"ok", b""))
        }
    }
}

/// 从真实 Component 摘要生成可信扫描结果，并记录调用次数。
#[derive(Debug)]
struct RecordingInspector {
    calls: Rc<Cell<usize>>,
    wrong_binding: bool,
}

impl ComponentInspector for RecordingInspector {
    fn inspect(
        &mut self,
        request: &ComponentInspectionRequest,
    ) -> Result<TrustedComponentInspection, ComponentInspectorFailure> {
        self.calls.set(self.calls.get() + 1);
        let component_digest = if self.wrong_binding {
            digest(b"wrong-component")
        } else {
            request.component_digest.clone()
        };
        Ok(TrustedComponentInspection {
            interface: ComponentInterfaceSnapshot {
                schema_version: COMPONENT_INTERFACE_SNAPSHOT_SCHEMA_VERSION,
                plugin_id: request.plugin_id.clone(),
                component_digest,
                world: "ascnet:lucia/plugin@0.1.0".to_string(),
                imports: Vec::new(),
                exports: vec!["ascnet:lucia/plugin.run".to_string()],
                scanner_revision: digest(b"scanner-v1"),
            },
            capabilities: CapabilityProfile::new(
                PluginCapabilitySet::empty(),
                PluginCapabilitySet::empty(),
            )
            .expect("空能力 Profile 应合法"),
        })
    }
}

/// 返回可观察调用次数的合法扫描器。
fn inspector() -> (RecordingInspector, Rc<Cell<usize>>) {
    let calls = Rc::new(Cell::new(0));
    (
        RecordingInspector {
            calls: Rc::clone(&calls),
            wrong_binding: false,
        },
        calls,
    )
}

/// 两次独立固定流水线摘要一致时才应生成可发布的 reproducible Attestation。
#[test]
fn runs_two_isolated_fixed_pipelines_and_attests_reproducibility() {
    let workspace = TestRoot::new("workspace-success");
    let scratch = TestRoot::new("scratch-success");
    let workspace_path = workspace.0.clone();
    let (inspector, calls) = inspector();
    let mut worker = PluginBuilderWorker::new(
        worker_config(&scratch),
        RecordingRunner::default(),
        inspector,
    );
    let result = worker
        .build(build_request(dependency_plan(&workspace)))
        .expect("两次确定性构建应成功");

    assert!(result.attestation.reproducible);
    assert_eq!(result.attestation.plugin_id, PLUGIN_ID);
    assert_eq!(result.component_bytes, COMPONENT_BYTES);
    assert_eq!(result.steps.len(), 10);
    assert_eq!(calls.get(), 1, "双构建一致后只扫描一次真实产物");
    assert!(!workspace_path.exists(), "成功后应清理 Candidate 工作区");

    let requests = &worker.runner().requests;
    assert_eq!(requests.len(), 10);
    let expected = [
        vec!["--offline", "--frozen", "fmt", "--all", "--", "--check"],
        vec!["--offline", "--frozen", "check"],
        vec![
            "--offline",
            "--frozen",
            "clippy",
            "--all-targets",
            "--",
            "-D",
            "warnings",
        ],
        vec!["--offline", "--frozen", "test", "--all-targets"],
        vec![
            "--offline",
            "--frozen",
            "build",
            "--release",
            "--target",
            "wasm32-wasip2",
        ],
    ];
    for (index, request) in requests.iter().enumerate() {
        assert_eq!(request.program, PathBuf::from("/trusted/bin/cargo"));
        assert!(request.clear_environment);
        assert_eq!(request.timeout, Duration::from_secs(30));
        assert_eq!(request.arguments, expected[index % 5]);
        assert_eq!(
            request.environment.get("CARGO_NET_OFFLINE"),
            Some(&"true".to_string())
        );
        assert_eq!(
            request.environment.get("CARGO_TERM_COLOR"),
            Some(&"never".to_string())
        );
        assert!(!request.environment.contains_key("SECRET_TOKEN"));
    }
    assert_ne!(
        requests[0].environment.get("CARGO_HOME"),
        requests[5].environment.get("CARGO_HOME"),
        "重复构建必须使用独立 Cargo home"
    );
    assert_ne!(
        requests[0].environment.get("CARGO_TARGET_DIR"),
        requests[5].environment.get("CARGO_TARGET_DIR"),
        "重复构建必须使用独立 target"
    );
}

/// 任一步非零退出必须立即停止，跳过扫描并清理两类目录。
#[test]
fn stops_on_first_failed_step_and_cleans_owned_directories() {
    let workspace = TestRoot::new("workspace-step-failure");
    let scratch = TestRoot::new("scratch-step-failure");
    let workspace_path = workspace.0.clone();
    let (inspector, calls) = inspector();
    let runner = RecordingRunner {
        fail_at: Some(2),
        ..RecordingRunner::default()
    };
    let mut worker = PluginBuilderWorker::new(worker_config(&scratch), runner, inspector);
    assert!(matches!(
        worker.build(build_request(dependency_plan(&workspace))),
        Err(PluginBuilderWorkerError::StepFailed {
            step: PluginBuildStep::Clippy,
            ..
        })
    ));
    assert_eq!(worker.runner().requests.len(), 3);
    assert_eq!(calls.get(), 0);
    assert!(!workspace_path.exists());
}

/// Runner 超时/启动错误必须停止后续命令并执行同样的失败清理。
#[test]
fn fails_closed_on_runner_error() {
    let workspace = TestRoot::new("workspace-runner-failure");
    let scratch = TestRoot::new("scratch-runner-failure");
    let workspace_path = workspace.0.clone();
    let (inspector, calls) = inspector();
    let runner = RecordingRunner {
        runner_error_at: Some(1),
        ..RecordingRunner::default()
    };
    let mut worker = PluginBuilderWorker::new(worker_config(&scratch), runner, inspector);
    assert!(matches!(
        worker.build(build_request(dependency_plan(&workspace))),
        Err(PluginBuilderWorkerError::Runner {
            step: PluginBuildStep::Check,
            ..
        })
    ));
    assert_eq!(worker.runner().requests.len(), 2);
    assert_eq!(calls.get(), 0);
    assert!(!workspace_path.exists());
}

/// 任一命令改写固定 Cargo.lock 时，命令后复核必须在下一步前拒绝。
#[test]
fn detects_lockfile_tampering_between_steps() {
    let workspace = TestRoot::new("workspace-lock-tamper");
    let scratch = TestRoot::new("scratch-lock-tamper");
    let workspace_path = workspace.0.clone();
    let (inspector, calls) = inspector();
    let runner = RecordingRunner {
        tamper_lock_at: Some(0),
        ..RecordingRunner::default()
    };
    let mut worker = PluginBuilderWorker::new(worker_config(&scratch), runner, inspector);
    assert!(matches!(
        worker.build(build_request(dependency_plan(&workspace))),
        Err(PluginBuilderWorkerError::DependencyPolicy(_))
    ));
    assert_eq!(worker.runner().requests.len(), 1);
    assert_eq!(calls.get(), 0);
    assert!(!workspace_path.exists());
}

/// 两个独立 target 的 Component 摘要不同就不能生成 reproducible 证明。
#[test]
fn rejects_non_reproducible_component_outputs() {
    let workspace = TestRoot::new("workspace-nondeterministic");
    let scratch = TestRoot::new("scratch-nondeterministic");
    let (inspector, calls) = inspector();
    let runner = RecordingRunner {
        different_second_component: true,
        ..RecordingRunner::default()
    };
    let mut worker = PluginBuilderWorker::new(worker_config(&scratch), runner, inspector);
    assert!(matches!(
        worker.build(build_request(dependency_plan(&workspace))),
        Err(PluginBuilderWorkerError::ReproducibilityMismatch)
    ));
    assert_eq!(worker.runner().requests.len(), 10);
    assert_eq!(calls.get(), 0);
}

/// 扫描器返回错绑摘要时必须拒绝证明，不能回退到 Candidate 自报接口。
#[test]
fn rejects_component_inspector_digest_misbinding() {
    let workspace = TestRoot::new("workspace-scan-mismatch");
    let scratch = TestRoot::new("scratch-scan-mismatch");
    let calls = Rc::new(Cell::new(0));
    let inspector = RecordingInspector {
        calls: Rc::clone(&calls),
        wrong_binding: true,
    };
    let mut worker = PluginBuilderWorker::new(
        worker_config(&scratch),
        RecordingRunner::default(),
        inspector,
    );
    assert!(matches!(
        worker.build(build_request(dependency_plan(&workspace))),
        Err(PluginBuilderWorkerError::InspectionBindingMismatch)
    ));
    assert_eq!(calls.get(), 1);
}

/// 非白名单环境键必须在创建任何子目录或运行命令前失败。
#[test]
fn rejects_environment_outside_explicit_allowlist() {
    let workspace = TestRoot::new("workspace-env-reject");
    let scratch = TestRoot::new("scratch-env-reject");
    let mut config = worker_config(&scratch);
    config
        .environment
        .insert("SECRET_TOKEN".to_string(), "secret".to_string());
    let (inspector, calls) = inspector();
    let mut worker = PluginBuilderWorker::new(config, RecordingRunner::default(), inspector);
    assert!(matches!(
        worker.build(build_request(dependency_plan(&workspace))),
        Err(PluginBuilderWorkerError::InvalidConfig(_))
    ));
    assert!(worker.runner().requests.is_empty());
    assert_eq!(calls.get(), 0);
}

/// 真实 Runner 必须在固定时限后终止并 wait，而不是无限等待子进程。
#[test]
fn real_runner_kills_and_waits_after_timeout() {
    let shell = PathBuf::from("/bin/sh");
    if !shell.exists() {
        return;
    }
    let mut runner = RealProcessRunner;
    let request = ProcessRequest {
        program: shell,
        arguments: vec!["-c".to_string(), "sleep 5".to_string()],
        current_directory: std::env::temp_dir(),
        clear_environment: true,
        environment: BTreeMap::new(),
        timeout: Duration::from_millis(30),
    };
    let started = Instant::now();
    assert!(runner.run(&request).is_err());
    assert!(
        started.elapsed() < Duration::from_secs(2),
        "超时进程应被及时终止并回收"
    );
}

/// 真实 Worker 必须用清空环境后的固定 Cargo 流水线完成两次离线构建并生成同摘要 WASM。
#[test]
fn real_worker_builds_reproducible_wasm_in_isolated_directories() {
    let sysroot = std::process::Command::new("rustc")
        .args(["--print", "sysroot"])
        .output()
        .expect("读取当前 Rust sysroot")
        .stdout;
    let sysroot = PathBuf::from(
        String::from_utf8(sysroot)
            .expect("Rust sysroot 应为 UTF-8")
            .trim(),
    );
    let bin = sysroot.join("bin");
    let cargo = bin.join("cargo");
    let rustc = bin.join("rustc");
    let rustdoc = bin.join("rustdoc");
    for executable in [&cargo, &rustc, &rustdoc] {
        let metadata = fs::symlink_metadata(executable).expect("工具链可执行文件应存在");
        assert!(
            metadata.is_file() && !metadata.file_type().is_symlink(),
            "真实 Worker 只接受非符号链接工具链文件"
        );
    }

    let workspace = TestRoot::new("workspace-real-build");
    let scratch = TestRoot::new("scratch-real-build");
    let plan = dependency_plan(&workspace);
    let (inspector, calls) = inspector();
    let mut worker = PluginBuilderWorker::new(
        PluginBuilderWorkerConfig {
            cargo_executable: cargo,
            scratch_parent: scratch.0.clone(),
            builder_revision: digest(b"real-builder-v1"),
            environment: BTreeMap::from([
                ("PATH".into(), format!("{}:/usr/bin:/bin", bin.display())),
                ("RUSTC".into(), rustc.display().to_string()),
                ("RUSTDOC".into(), rustdoc.display().to_string()),
                ("SOURCE_DATE_EPOCH".into(), "1".into()),
            ]),
            step_timeout: Duration::from_secs(120),
        },
        RealProcessRunner,
        inspector,
    );
    let result = worker
        .build(build_request(plan))
        .expect("真实隔离 Worker 应完成两次固定流水线");
    assert!(result.attestation.reproducible);
    assert!(result.component_bytes.starts_with(b"\0asm"));
    assert_eq!(result.steps.len(), 10);
    assert_eq!(calls.get(), 1);
}
